apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guest-check
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guest-check
    spec:
      containers:
        - name: guest-check
          image: java:8
          command: ["java", "-jar", "java/guest-check.jar"]
          volumeMounts:
          - mountPath: "/java"
            name: code
            subPath: guest/guest-check
          - mountPath: "/etc/localtime"
            name: tz-config
          ports:
            - containerPort: 8080
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code-claims
        - name: tz-config
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: guest-check
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: guest-check
