apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guest-protocol
  namespace: airportcloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guest-protocol
    spec:
      containers:
        - name: guest-protocol
          image: java:8
          command: ["java","-jar","java/guest-protocol.jar"]
          volumeMounts:
          - mountPath: "/java"
            name: code
            subPath: airportcloud/guest-protocol
          - mountPath: "/etc/localtime"
            name: tz-config
          ports:
            - containerPort: 8080
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: pvc-airportcloud
        - name: tz-config
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: guest-protocol
  namespace: airportcloud
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: guest-protocol
