apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guest-protocol
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guest-protocol
    spec:
      containers:
        - name: guest-protocol
          image: java:8-jre-alpine
          command: ["java","-jar","/code/guest-protocol-1.0.jar"]
          volumeMounts:
          - mountPath: "/code"
            name: code
            subPath: guest/guest-protocol
          ports:
            - containerPort: 8080
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code-claims
---
apiVersion: v1
kind: Service
metadata:
  name: guest-protocol
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: guest-protocol