apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airportcloud
  namespace: airportcloud
  labels:
    branch: master
    type: code
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/nfs-share/code
    server: 192.168.142.48
