apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airportcloud
  namespace: airportcloud
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5G
  selector:
    matchLabels:
      branch: master
      type: code