apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: institution-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: institution-client
    spec:
      containers:
        - name: institution-client
          image: java:8-jre-alpine
          command: ["java","-jar","/code/institution-client-1.0-SNAPSHOT.jar"]
          volumeMounts:
          - mountPath: "/code"
            name: code
            subPath: guest/institution-client
          ports:
            - containerPort: 8080
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code-claims
---
apiVersion: v1
kind: Service
metadata:
  name: institution-client
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: institution-client